const quotes = [
"Believe in yourself and all that you are.",
"Push yourself, because no one else will do it for you.",
"Success doesn’t just find you—you have to go out and get it.",
"Dream it. Wish it. Do it.",
"Stay positive, work hard, make it happen.",
"Don’t stop until you’re proud.",
"Your only limit is your mind.",
"Great things never come from comfort zones.",
"Wake up with determination. Go to bed with satisfaction.",
"Do something today that your future self will thank you for.",
"Little things make big days.",
"It’s going to be hard, but hard does not mean impossible.",
"Don’t wait for opportunity. Create it.",
"Sometimes later becomes never. Do it now.",
"Success is what comes after you stop making excuses.",
"Work hard in silence, let success make the noise.",
"Dream bigger. Do bigger.",
"Don’t watch the clock; do what it does. Keep going.",
"Keep going. Everything you need will come to you.",
"Start where you are. Use what you have. Do what you can.",
"Opportunities don’t happen, you create them.",
"Success is not for the lazy.",
"The harder you work, the luckier you get.",
"Don’t limit your challenges, challenge your limits.",
"Success is not final, failure is not fatal: it is the courage to continue that counts.",
"Believe you can and you’re halfway there.",
"Act as if what you do makes a difference. It does.",
"Success usually comes to those who are too busy to be looking for it.",
"Don’t be afraid to give up the good to go for the great.",
"I find that the harder I work, the more luck I seem to have.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"The secret of getting ahead is getting started.",
"You don’t have to be great to start, but you have to start to be great.",
"Don’t let yesterday take up too much of today.",
"You learn more from failure than from success.",
"It always seems impossible until it’s done.",
"If you are not willing to risk the usual, you will have to settle for the ordinary.",
"Try not to become a person of success, but rather try to become a person of value.",
"All progress takes place outside the comfort zone.",
"Success is liking yourself, liking what you do, and liking how you do it.",
"Hardships often prepare ordinary people for an extraordinary destiny.",
"Don’t be pushed around by the fears in your mind.",
"Great minds discuss ideas; average minds discuss events; small minds discuss people.",
"If you want to achieve greatness stop asking for permission.",
"Things work out best for those who make the best of how things work out.",
"Don’t let what you cannot do interfere with what you can do.",
"You don’t find the will to win—you create it.",
"Do what you can with all you have, wherever you are.",
"Small progress is still progress.",
"Stay focused and never give up.",
"Discipline is the bridge between goals and accomplishment.",
"Don’t quit. Suffer now and be a champion forever.",
"Make each day your masterpiece.",
"Turn your wounds into wisdom.",
"What you get by achieving your goals is not as important as what you become.",
"Everything you’ve ever wanted is on the other side of fear.",
"Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
"Be stronger than your excuses.",
"Focus on your goal. Don’t look in any direction but ahead.",
"The key to success is to focus on goals, not obstacles.",
"Failure is not the opposite of success; it’s part of success.",
"You are capable of amazing things.",
"Don’t downgrade your dream just to fit your reality.",
"Your passion is waiting for your courage to catch up.",
"Magic is believing in yourself.",
"If something is important enough, even if the odds are against you, you should still do it.",
"Don’t wish it were easier. Wish you were better.",
"Success is not in what you have, but who you are.",
"Start each day with a positive thought.",
"Be so good they can’t ignore you.",
"Quality is not an act, it is a habit.",
"Well done is better than well said.",
"Success is how high you bounce when you hit bottom.",
"Don’t be afraid to start over. It’s a new chance to rebuild what you want.",
"Push harder than yesterday if you want a different tomorrow.",
"Great things take time.",
"Be fearless in the pursuit of what sets your soul on fire.",
"Consistency is what transforms average into excellence.",
"Your limitation—it’s only your imagination.",
"Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
"Dream it. Believe it. Build it.",
"Be the energy you want to attract.",
"You didn’t come this far to only come this far.",
"The best way to predict the future is to create it.",
"If you get tired, learn to rest, not to quit.",
"Don’t stop when you’re tired. Stop when you’re done.",
"Every accomplishment starts with the decision to try.",
"Action is the foundational key to all success.",
"Success is the sum of small efforts repeated day in and day out.",
"The difference between ordinary and extraordinary is that little extra.",
"Be patient. Great things take time.",
"Never give up. Great things take time.",
"Stay hungry. Stay foolish.",
"Work until your idols become your rivals.",
"Your dreams don’t work unless you do.",
"Go the extra mile. It’s never crowded.",
"Turn your dreams into plans.",
"Be proud of how far you’ve come."
];

let click=document.getElementById("button");
let quote=document.getElementById("quote");

click.addEventListener("click",function(){
    let turn=Math.floor(Math.random()*quotes.length);
    quote.innerText=quotes[turn];


});
